import { Inter } from "next/font/google";
import "./globals.css";
import StoreWrapper from "./storeWrapper";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Ch",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreWrapper>{children}</StoreWrapper>
      </body>
    </html>
  );
}
